### ISSUE TITLE
I run aql but I faced raise error  Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib"

### ISSUE THREAD

**Issue by kgneng2** [aerospike/aql#22] opened 2023-04-12 07:34 UTC
my computer is m2

I alias libssl.1.1.dylib files.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/7286378/231385368-4ced1d77-181e-456f-bbb1-2cd9526c16fe.png">

But Library not loaded... why?? 

```
➜  ~ aql
dyld[19680]: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: <6498F857-F3A0-39C4-BB32-1C4E7DDAA008> /usr/local/aerospike/bin/aql
  Reason: tried: '/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib' (no such file), '/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/lib/libssl.1.1.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/openssl@1.1/1.1.1t/lib/libssl.1.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openssl@1.1/1.1.1t/lib/libssl.1.1.dylib' (no such file), '/opt/homebrew/Cellar/openssl@1.1/1.1.1t/lib/libssl.1.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/lib/libssl.1.1.dylib' (no such file, not in dyld cache)
[1]    19680 abort      aql
➜  ~ cd /usr/local/opt/openssl@1.1/lib/
➜  lib git:(stable) ls
engines-1.1         libcrypto.1.1.dylib libcrypto.a         libcrypto.dylib     libssl.1.1.dylib    libssl.a            libssl.dylib        pkgconfig
➜  lib git:(stable) cd /opt/homebrew/Cellar/openssl@1.1/1.1.1t/lib
➜  lib git:(stable) ls
engines-1.1         libcrypto.1.1.dylib libcrypto.a         libcrypto.dylib     libssl.1.1.dylib    libssl.a            libssl.dylib        pkgconfig
```

**Comment by jdogmcsteezy** [comment] 2023-04-12 20:28
Hey @kgneng2, what version of aql are you using? Did you build it yourself or did you download the aerospike-tools package? This error seems to imply you are using a build that was intended for macOS x86 and not macOS M1/2:
```
but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

**Comment by jdogmcsteezy** [comment] 2023-05-11 19:28
Closing. Please re-open if the issue persists

**Closed by jdogmcsteezy** 2023-05-11 19:28 UTC
